version: '3.9'

services:

  # web service using ngix
  nginx:

    container_name: nginx_server

    image: nginx:latest
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf # mount the nginx config file
      - ./FrontEnd:/usr/share/nginx/html # mount the front end files(html/css/scss/js)
    ports:
      - "80:80" # port being listened on

  # the application container
  flask_app:

    container_name: flask_app

    image: justingav/flask_live_app:latest

    build: .

    ports:
      # ports being listened on
      - "4000:4000"

    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres

    depends_on:
      # the database being used
      - flask_db

  # the database container
  flask_db:

    container_name: flask_db

    image: postgres:latest

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
