name: CI for API app

on: # Select branches to preform actions and conditions for actions to be preformed.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Build and push Docker image # Build and push docker image.
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Dockerfile 
        push: true
        tags: |
          justingav/flask_live_app:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    
